vlog -work work C:/altera/13.0sp1/FILES/Lab6/simulation/modelsim/CPUwaveform.vwf.vt
vsim -novopt -c -t 1ps -L cycloneii_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.CPU_vlg_vec_tst
onerror {resume}
add wave {CPU_vlg_vec_tst/i1/A}
add wave {CPU_vlg_vec_tst/i1/A[7]}
add wave {CPU_vlg_vec_tst/i1/A[6]}
add wave {CPU_vlg_vec_tst/i1/A[5]}
add wave {CPU_vlg_vec_tst/i1/A[4]}
add wave {CPU_vlg_vec_tst/i1/A[3]}
add wave {CPU_vlg_vec_tst/i1/A[2]}
add wave {CPU_vlg_vec_tst/i1/A[1]}
add wave {CPU_vlg_vec_tst/i1/A[0]}
add wave {CPU_vlg_vec_tst/i1/B}
add wave {CPU_vlg_vec_tst/i1/B[7]}
add wave {CPU_vlg_vec_tst/i1/B[6]}
add wave {CPU_vlg_vec_tst/i1/B[5]}
add wave {CPU_vlg_vec_tst/i1/B[4]}
add wave {CPU_vlg_vec_tst/i1/B[3]}
add wave {CPU_vlg_vec_tst/i1/B[2]}
add wave {CPU_vlg_vec_tst/i1/B[1]}
add wave {CPU_vlg_vec_tst/i1/B[0]}
add wave {CPU_vlg_vec_tst/i1/clk}
add wave {CPU_vlg_vec_tst/i1/data_in}
add wave {CPU_vlg_vec_tst/i1/EN}
add wave {CPU_vlg_vec_tst/i1/first4}
add wave {CPU_vlg_vec_tst/i1/first4[6]}
add wave {CPU_vlg_vec_tst/i1/first4[5]}
add wave {CPU_vlg_vec_tst/i1/first4[4]}
add wave {CPU_vlg_vec_tst/i1/first4[3]}
add wave {CPU_vlg_vec_tst/i1/first4[2]}
add wave {CPU_vlg_vec_tst/i1/first4[1]}
add wave {CPU_vlg_vec_tst/i1/first4[0]}
add wave {CPU_vlg_vec_tst/i1/last4}
add wave {CPU_vlg_vec_tst/i1/last4[6]}
add wave {CPU_vlg_vec_tst/i1/last4[5]}
add wave {CPU_vlg_vec_tst/i1/last4[4]}
add wave {CPU_vlg_vec_tst/i1/last4[3]}
add wave {CPU_vlg_vec_tst/i1/last4[2]}
add wave {CPU_vlg_vec_tst/i1/last4[1]}
add wave {CPU_vlg_vec_tst/i1/last4[0]}
add wave {CPU_vlg_vec_tst/i1/leds0}
add wave {CPU_vlg_vec_tst/i1/leds1}
add wave {CPU_vlg_vec_tst/i1/leds2}
add wave {CPU_vlg_vec_tst/i1/leds3}
add wave {CPU_vlg_vec_tst/i1/leds4}
add wave {CPU_vlg_vec_tst/i1/leds5}
add wave {CPU_vlg_vec_tst/i1/leds6}
add wave {CPU_vlg_vec_tst/i1/leds30}
add wave {CPU_vlg_vec_tst/i1/leds31}
add wave {CPU_vlg_vec_tst/i1/leds32}
add wave {CPU_vlg_vec_tst/i1/leds33}
add wave {CPU_vlg_vec_tst/i1/leds34}
add wave {CPU_vlg_vec_tst/i1/leds35}
add wave {CPU_vlg_vec_tst/i1/leds36}
add wave {CPU_vlg_vec_tst/i1/res1}
add wave {CPU_vlg_vec_tst/i1/res2}
add wave {CPU_vlg_vec_tst/i1/reset}
run -all
